# Generated by Django 3.1.3 on 2020-11-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_auto_20201118_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafes',
            name='address',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='cafes',
            name='instagram',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cafes',
            name='website',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
