# Generated by Django 3.1.3 on 2020-11-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_auto_20201119_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafes',
            name='address',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
